### ISSUE TITLE
Verify the app and remove the affiliation disclaimer

### ISSUE THREAD

**Issue by Newbytee** [flathub/se.cendio.tlclient#17]
While we were working on this in a more active fashion, there were mentions of maybe removing the "This package is not verified by, affiliated with, or supported by Cendio AB." disclaimer from the app's description. However, this never materialised, and the disclaimer remains there. Since then, Flathub has also introduced a verification system. I think that if we remove this, it would also make sense to verify the app.

@CendioOssman, @samhed, what do you think of this?

**Comment by CendioOssman** [comment]
As long as the package isn't maintained and tested by Cendio, then I think some form of disclaimer should be in place. Same for the verification, as I would assume that it is there to clearly show that it is fully maintained by the authors of the application.

This is assuming that the maintainership remains the same. If Cendio took over the package, then it would be natural to change those things.

Having it community maintained is preferred from our side presently, though. Mainly because there were some things that do not work correctly in flatpak. So, the client could never be fully supported by us anyway. We'd have to add a different disclaimer if we were to take over responsibility, or make a flatpak specific version with the unreliable features removed.

**Comment by Newbytee** [comment]
Makes sense. I'll close this then. Thanks for clarifying!
